import React, { useState } from 'react'
import { View, Text, FlatList } from 'react-native'
import Hour from './Hour'

const HourList = () => {
    const [data, setData] = useState([
        {
            "time_epoch": 1655154000,
            "time": "2022-06-14 00:00",
            "temp_c": 19.3,
            "temp_f": 66.7,
            "is_day": 0,
            "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 323,
            "wind_dir": "NW",
            "pressure_mb": 1015.0,
            "pressure_in": 29.97,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 64,
            "cloud": 25,
            "feelslike_c": 19.3,
            "feelslike_f": 66.7,
            "windchill_c": 19.3,
            "windchill_f": 66.7,
            "heatindex_c": 19.3,
            "heatindex_f": 66.7,
            "dewpoint_c": 12.4,
            "dewpoint_f": 54.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 20.6,
            "gust_kph": 33.1,
            "uv": 1.0
        },
        {
            "time_epoch": 1655157600,
            "time": "2022-06-14 01:00",
            "temp_c": 18.6,
            "temp_f": 65.5,
            "is_day": 0,
            "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 332,
            "wind_dir": "NNW",
            "pressure_mb": 1015.0,
            "pressure_in": 29.98,
            "precip_mm": 0.1,
            "precip_in": 0.0,
            "humidity": 73,
            "cloud": 82,
            "feelslike_c": 18.6,
            "feelslike_f": 65.5,
            "windchill_c": 18.6,
            "windchill_f": 65.5,
            "heatindex_c": 18.6,
            "heatindex_f": 65.5,
            "dewpoint_c": 13.7,
            "dewpoint_f": 56.7,
            "will_it_rain": 1,
            "chance_of_rain": 76,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 18.6,
            "gust_kph": 29.9,
            "uv": 1.0
        },
        {
            "time_epoch": 1655161200,
            "time": "2022-06-14 02:00",
            "temp_c": 17.4,
            "temp_f": 63.3,
            "is_day": 0,
            "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 340,
            "wind_dir": "NNW",
            "pressure_mb": 1016.0,
            "pressure_in": 29.99,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 81,
            "cloud": 11,
            "feelslike_c": 17.4,
            "feelslike_f": 63.3,
            "windchill_c": 17.4,
            "windchill_f": 63.3,
            "heatindex_c": 17.4,
            "heatindex_f": 63.3,
            "dewpoint_c": 14.1,
            "dewpoint_f": 57.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 1.0
        },
        {
            "time_epoch": 1655164800,
            "time": "2022-06-14 03:00",
            "temp_c": 16.3,
            "temp_f": 61.3,
            "is_day": 0,
            "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 347,
            "wind_dir": "NNW",
            "pressure_mb": 1016.0,
            "pressure_in": 30.0,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 88,
            "cloud": 14,
            "feelslike_c": 16.3,
            "feelslike_f": 61.3,
            "windchill_c": 16.3,
            "windchill_f": 61.3,
            "heatindex_c": 16.3,
            "heatindex_f": 61.3,
            "dewpoint_c": 14.2,
            "dewpoint_f": 57.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.1,
            "gust_kph": 22.7,
            "uv": 1.0
        },
        {
            "time_epoch": 1655168400,
            "time": "2022-06-14 04:00",
            "temp_c": 15.8,
            "temp_f": 60.4,
            "is_day": 0,
            "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 330,
            "wind_dir": "NNW",
            "pressure_mb": 1016.0,
            "pressure_in": 30.01,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 92,
            "cloud": 20,
            "feelslike_c": 15.8,
            "feelslike_f": 60.4,
            "windchill_c": 15.8,
            "windchill_f": 60.4,
            "heatindex_c": 15.8,
            "heatindex_f": 60.4,
            "dewpoint_c": 14.5,
            "dewpoint_f": 58.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.2,
            "gust_kph": 21.2,
            "uv": 1.0
        },
        {
            "time_epoch": 1655172000,
            "time": "2022-06-14 05:00",
            "temp_c": 15.3,
            "temp_f": 59.5,
            "is_day": 0,
            "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 339,
            "wind_dir": "NNW",
            "pressure_mb": 1017.0,
            "pressure_in": 30.02,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 92,
            "cloud": 7,
            "feelslike_c": 15.3,
            "feelslike_f": 59.5,
            "windchill_c": 15.3,
            "windchill_f": 59.5,
            "heatindex_c": 15.3,
            "heatindex_f": 59.5,
            "dewpoint_c": 13.9,
            "dewpoint_f": 57.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.6,
            "gust_kph": 22.0,
            "uv": 1.0
        },
        {
            "time_epoch": 1655175600,
            "time": "2022-06-14 06:00",
            "temp_c": 14.9,
            "temp_f": 58.8,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 340,
            "wind_dir": "NNW",
            "pressure_mb": 1017.0,
            "pressure_in": 30.04,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 81,
            "cloud": 4,
            "feelslike_c": 14.0,
            "feelslike_f": 57.2,
            "windchill_c": 14.0,
            "windchill_f": 57.2,
            "heatindex_c": 14.9,
            "heatindex_f": 58.8,
            "dewpoint_c": 11.6,
            "dewpoint_f": 52.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.1,
            "gust_kph": 22.7,
            "uv": 4.0
        },
        {
            "time_epoch": 1655179200,
            "time": "2022-06-14 07:00",
            "temp_c": 16.1,
            "temp_f": 61.0,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 356,
            "wind_dir": "N",
            "pressure_mb": 1018.0,
            "pressure_in": 30.06,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 72,
            "cloud": 0,
            "feelslike_c": 16.1,
            "feelslike_f": 61.0,
            "windchill_c": 16.1,
            "windchill_f": 61.0,
            "heatindex_c": 16.1,
            "heatindex_f": 61.0,
            "dewpoint_c": 11.1,
            "dewpoint_f": 52.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 5.0
        },
        {
            "time_epoch": 1655182800,
            "time": "2022-06-14 08:00",
            "temp_c": 18.1,
            "temp_f": 64.6,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 11.6,
            "wind_kph": 18.7,
            "wind_degree": 357,
            "wind_dir": "N",
            "pressure_mb": 1019.0,
            "pressure_in": 30.08,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 61,
            "cloud": 1,
            "feelslike_c": 18.1,
            "feelslike_f": 64.6,
            "windchill_c": 18.1,
            "windchill_f": 64.6,
            "heatindex_c": 18.1,
            "heatindex_f": 64.6,
            "dewpoint_c": 10.6,
            "dewpoint_f": 51.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 5.0
        },
        {
            "time_epoch": 1655186400,
            "time": "2022-06-14 09:00",
            "temp_c": 20.1,
            "temp_f": 68.2,
            "is_day": 1,
            "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 358,
            "wind_dir": "N",
            "pressure_mb": 1019.0,
            "pressure_in": 30.09,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 50,
            "cloud": 56,
            "feelslike_c": 20.1,
            "feelslike_f": 68.2,
            "windchill_c": 20.1,
            "windchill_f": 68.2,
            "heatindex_c": 20.1,
            "heatindex_f": 68.2,
            "dewpoint_c": 9.3,
            "dewpoint_f": 48.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 6.0
        },
        {
            "time_epoch": 1655190000,
            "time": "2022-06-14 10:00",
            "temp_c": 21.5,
            "temp_f": 70.7,
            "is_day": 1,
            "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
            },
            "wind_mph": 13.4,
            "wind_kph": 21.6,
            "wind_degree": 0,
            "wind_dir": "N",
            "pressure_mb": 1019.0,
            "pressure_in": 30.09,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 44,
            "cloud": 47,
            "feelslike_c": 21.5,
            "feelslike_f": 70.7,
            "windchill_c": 21.5,
            "windchill_f": 70.7,
            "heatindex_c": 24.1,
            "heatindex_f": 75.4,
            "dewpoint_c": 8.8,
            "dewpoint_f": 47.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.4,
            "gust_kph": 24.8,
            "uv": 6.0
        },
        {
            "time_epoch": 1655193600,
            "time": "2022-06-14 11:00",
            "temp_c": 23.1,
            "temp_f": 73.6,
            "is_day": 1,
            "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
            },
            "wind_mph": 12.8,
            "wind_kph": 20.5,
            "wind_degree": 356,
            "wind_dir": "N",
            "pressure_mb": 1019.0,
            "pressure_in": 30.09,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 39,
            "cloud": 85,
            "feelslike_c": 24.3,
            "feelslike_f": 75.7,
            "windchill_c": 23.1,
            "windchill_f": 73.6,
            "heatindex_c": 24.3,
            "heatindex_f": 75.7,
            "dewpoint_c": 8.5,
            "dewpoint_f": 47.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.8,
            "gust_kph": 23.8,
            "uv": 5.0
        },
        {
            "time_epoch": 1655197200,
            "time": "2022-06-14 12:00",
            "temp_c": 24.4,
            "temp_f": 75.9,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 12.8,
            "wind_kph": 20.5,
            "wind_degree": 348,
            "wind_dir": "NNW",
            "pressure_mb": 1019.0,
            "pressure_in": 30.09,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 37,
            "cloud": 6,
            "feelslike_c": 24.8,
            "feelslike_f": 76.6,
            "windchill_c": 24.4,
            "windchill_f": 75.9,
            "heatindex_c": 24.8,
            "heatindex_f": 76.6,
            "dewpoint_c": 8.6,
            "dewpoint_f": 47.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.8,
            "gust_kph": 23.8,
            "uv": 6.0
        },
        {
            "time_epoch": 1655200800,
            "time": "2022-06-14 13:00",
            "temp_c": 24.5,
            "temp_f": 76.1,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 13.0,
            "wind_kph": 20.9,
            "wind_degree": 343,
            "wind_dir": "NNW",
            "pressure_mb": 1019.0,
            "pressure_in": 30.09,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 34,
            "cloud": 16,
            "feelslike_c": 24.7,
            "feelslike_f": 76.5,
            "windchill_c": 24.5,
            "windchill_f": 76.1,
            "heatindex_c": 24.7,
            "heatindex_f": 76.5,
            "dewpoint_c": 7.8,
            "dewpoint_f": 46.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.0,
            "gust_kph": 24.1,
            "uv": 6.0
        },
        {
            "time_epoch": 1655204400,
            "time": "2022-06-14 14:00",
            "temp_c": 24.9,
            "temp_f": 76.8,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 12.1,
            "wind_kph": 19.4,
            "wind_degree": 340,
            "wind_dir": "NNW",
            "pressure_mb": 1019.0,
            "pressure_in": 30.08,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 32,
            "cloud": 15,
            "feelslike_c": 24.8,
            "feelslike_f": 76.6,
            "windchill_c": 24.9,
            "windchill_f": 76.8,
            "heatindex_c": 24.8,
            "heatindex_f": 76.6,
            "dewpoint_c": 7.2,
            "dewpoint_f": 45.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 6.0
        },
        {
            "time_epoch": 1655208000,
            "time": "2022-06-14 15:00",
            "temp_c": 25.4,
            "temp_f": 77.7,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 11.0,
            "wind_kph": 17.6,
            "wind_degree": 341,
            "wind_dir": "NNW",
            "pressure_mb": 1018.0,
            "pressure_in": 30.06,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 32,
            "cloud": 15,
            "feelslike_c": 25.1,
            "feelslike_f": 77.2,
            "windchill_c": 25.4,
            "windchill_f": 77.7,
            "heatindex_c": 25.1,
            "heatindex_f": 77.2,
            "dewpoint_c": 7.3,
            "dewpoint_f": 45.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 12.5,
            "gust_kph": 20.2,
            "uv": 7.0
        },
        {
            "time_epoch": 1655211600,
            "time": "2022-06-14 16:00",
            "temp_c": 25.5,
            "temp_f": 77.9,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 343,
            "wind_dir": "NNW",
            "pressure_mb": 1018.0,
            "pressure_in": 30.06,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 32,
            "cloud": 15,
            "feelslike_c": 25.2,
            "feelslike_f": 77.4,
            "windchill_c": 25.5,
            "windchill_f": 77.9,
            "heatindex_c": 25.2,
            "heatindex_f": 77.4,
            "dewpoint_c": 7.5,
            "dewpoint_f": 45.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 12.3,
            "gust_kph": 19.8,
            "uv": 7.0
        },
        {
            "time_epoch": 1655215200,
            "time": "2022-06-14 17:00",
            "temp_c": 25.3,
            "temp_f": 77.5,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 10.1,
            "wind_kph": 16.2,
            "wind_degree": 358,
            "wind_dir": "N",
            "pressure_mb": 1018.0,
            "pressure_in": 30.05,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 33,
            "cloud": 15,
            "feelslike_c": 25.1,
            "feelslike_f": 77.2,
            "windchill_c": 25.3,
            "windchill_f": 77.5,
            "heatindex_c": 25.1,
            "heatindex_f": 77.2,
            "dewpoint_c": 7.7,
            "dewpoint_f": 45.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 7.0
        },
        {
            "time_epoch": 1655218800,
            "time": "2022-06-14 18:00",
            "temp_c": 24.6,
            "temp_f": 76.3,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 18,
            "wind_dir": "NNE",
            "pressure_mb": 1018.0,
            "pressure_in": 30.05,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 36,
            "cloud": 15,
            "feelslike_c": 24.9,
            "feelslike_f": 76.8,
            "windchill_c": 24.6,
            "windchill_f": 76.3,
            "heatindex_c": 24.9,
            "heatindex_f": 76.8,
            "dewpoint_c": 8.6,
            "dewpoint_f": 47.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 6.0
        },
        {
            "time_epoch": 1655222400,
            "time": "2022-06-14 19:00",
            "temp_c": 22.7,
            "temp_f": 72.9,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 38,
            "wind_dir": "NE",
            "pressure_mb": 1018.0,
            "pressure_in": 30.05,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 44,
            "cloud": 16,
            "feelslike_c": 24.4,
            "feelslike_f": 75.9,
            "windchill_c": 22.7,
            "windchill_f": 72.9,
            "heatindex_c": 24.4,
            "heatindex_f": 75.9,
            "dewpoint_c": 9.9,
            "dewpoint_f": 49.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 6.0
        },
        {
            "time_epoch": 1655226000,
            "time": "2022-06-14 20:00",
            "temp_c": 19.3,
            "temp_f": 66.7,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 57,
            "wind_dir": "ENE",
            "pressure_mb": 1018.0,
            "pressure_in": 30.06,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 48,
            "cloud": 13,
            "feelslike_c": 19.3,
            "feelslike_f": 66.7,
            "windchill_c": 19.3,
            "windchill_f": 66.7,
            "heatindex_c": 19.3,
            "heatindex_f": 66.7,
            "dewpoint_c": 8.0,
            "dewpoint_f": 46.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 5.0
        },
        {
            "time_epoch": 1655229600,
            "time": "2022-06-14 21:00",
            "temp_c": 17.2,
            "temp_f": 63.0,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 1.6,
            "wind_kph": 2.5,
            "wind_degree": 51,
            "wind_dir": "NE",
            "pressure_mb": 1019.0,
            "pressure_in": 30.09,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 51,
            "cloud": 13,
            "feelslike_c": 17.2,
            "feelslike_f": 63.0,
            "windchill_c": 17.2,
            "windchill_f": 63.0,
            "heatindex_c": 17.2,
            "heatindex_f": 63.0,
            "dewpoint_c": 6.9,
            "dewpoint_f": 44.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.4,
            "gust_kph": 5.4,
            "uv": 5.0
        },
        {
            "time_epoch": 1655233200,
            "time": "2022-06-14 22:00",
            "temp_c": 16.2,
            "temp_f": 61.2,
            "is_day": 0,
            "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 319,
            "wind_dir": "NW",
            "pressure_mb": 1019.0,
            "pressure_in": 30.1,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 54,
            "cloud": 13,
            "feelslike_c": 16.2,
            "feelslike_f": 61.2,
            "windchill_c": 16.2,
            "windchill_f": 61.2,
            "heatindex_c": 16.2,
            "heatindex_f": 61.2,
            "dewpoint_c": 6.8,
            "dewpoint_f": 44.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.9,
            "gust_kph": 14.4,
            "uv": 1.0
        },
        {
            "time_epoch": 1655236800,
            "time": "2022-06-14 23:00",
            "temp_c": 15.4,
            "temp_f": 59.7,
            "is_day": 0,
            "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 326,
            "wind_dir": "NNW",
            "pressure_mb": 1019.0,
            "pressure_in": 30.1,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 57,
            "cloud": 13,
            "feelslike_c": 15.4,
            "feelslike_f": 59.7,
            "windchill_c": 15.4,
            "windchill_f": 59.7,
            "heatindex_c": 15.4,
            "heatindex_f": 59.7,
            "dewpoint_c": 6.9,
            "dewpoint_f": 44.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 1.0
        }
    ]);

    const renderItem = (item) => {
        return (
            <View><Text>Lorem ipsum</Text></View>
        )
    }

    return (
        <View>
            <Text>Lorem ipsum</Text>
            <FlatList
                data={data}
                renderItem={renderItem}
            />
        </View>
    )
}

export default HourList